language: python
python:
    - 3.3
    - 3.4
    - 3.5
before_install:
    - pip install coveralls
install:
    - pip install -e .
    - pip install coverage
script: nosetests -w tests --with-coverage --cover-package=flask_reveal
after_success:
    - coveralls
